x-node-config: &node-config
  image: node:24-alpine
  user: "${HOST_UID}:${HOST_GID}"
  volumes:
    - ../app:/app
  working_dir: /app
  tty: true
  stdin_open: true
  init: true

services:
  api:
    image: clue/json-server
    container_name: json-server-container
    command: -w questions.json
    user: "${HOST_UID}:${HOST_GID}"
    ports:
      - "80:80"
    volumes:
      - ../app/data:/data
  npm:
    <<: *node-config
    container_name: npm-cli
    entrypoint:
      - npm
    environment:
      - WDS_SOCKET_PORT=0
      - HOST=0.0.0.0
      - WEBPACK_DEV_SERVER_WEBPACK_OPTIONS={\"watchOptions\":{\"followSymlinks\":true,\"poll\":1000}}
      - CHOKIDAR_INTERVAL=1000
      - REACT_APP_OMDB_API_KEY=${OMDB_API_KEY}

  npx:
    <<: *node-config
    container_name: npx-cli
    entrypoint:
      - npx
